---
- hosts: local
  connection: local
  gather_facts: False
  tasks:

  - name: delete s3 bucket and all contents
    aws_s3:
      bucket: "{{ bucket }}"
      region: "{{ region }}"
      mode: delete
