---
- hosts: local
  connection: local
  gather_facts: False
  tasks:

  - name: list keys
    aws_s3:
      bucket: "{{ bucket }}"
      mode: list
      # prefix: "{{ prefix }}"
      # marker: "{{ marker }}"
      # max_keys: "{{ max_keys }}"
    register: s3_list_keys
      
      
   - debug: msg="{{ s3_list_keys }}"
