---
- hosts: local
  connection: local
  gather_facts: False
  tasks:

  - name: put operation
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ object_path }}"
      src: "{{ src_path }}"
      mode: put
      # metadata: "{{ metadata }}"
      # headers: "{{ headers }}"
